# Generated by Django 5.2 on 2026-04-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата прибытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cargo_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cargo.cargocompany', verbose_name='Карго-компания')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=100, verbose_name='Трек-номер')),
                ('internal_number', models.CharField(blank=True, max_length=50, verbose_name='Внутренний номер')),
                ('shop', models.CharField(blank=True, max_length=200, verbose_name='Магазин')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вес (кг)')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за кг')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Итоговая стоимость')),
                ('delivery_status', models.CharField(choices=[('waiting', 'Ожидается на складе'), ('accepted', 'Принят на складе'), ('preparing', 'Подготовлен к отправке'), ('in_transit', 'В пути'), ('arrived', 'Прибыл в страну'), ('sorting', 'На сортировке'), ('ready', 'Готов к выдаче'), ('issued', 'Выдан клиенту'), ('problem', 'Проблема / Возврат')], default='waiting', max_length=20, verbose_name='Статус доставки')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Частично оплачен'), ('paid', 'Полностью оплачен')], default='unpaid', max_length=10, verbose_name='Статус оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий оператора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('sent_at', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('arrived_at', models.DateField(blank=True, null=True, verbose_name='Дата прибытия')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cargo_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cargo.cargocompany', verbose_name='Карго-компания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client', verbose_name='Клиент')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
