# Generated by Django 5.2 on 2026-04-22 20:24

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('clothes', 'Одежда'), ('shoes', 'Обувь'), ('accessories', 'Аксессуары'), ('electronics', 'Электроника'), ('home', 'Товары для дома'), ('cosmetics', 'Косметика'), ('auto', 'Автотовары'), ('kids', 'Детские товары'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('original_link', models.URLField(blank=True, verbose_name='Ссылка на оригинал')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='catalog/products/', verbose_name='Фото')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cargo_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cargo.cargocompany', verbose_name='Карго-компания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на товар')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('reviewing', 'На рассмотрении'), ('waiting_confirm', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('purchased', 'Выкуплена'), ('shipped', 'Передана в доставку')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='clients.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка на выкуп',
                'verbose_name_plural': 'Заявки на выкуп',
                'ordering': ['-created_at'],
            },
        ),
    ]
