# Generated by Django 5.2 on 2026-04-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название карго-компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cargo_logos/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон')),
                ('contact_telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('work_schedule', models.CharField(blank=True, max_length=255, verbose_name='Режим работы')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Валюта (короткий код)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Карго-компания',
                'verbose_name_plural': 'Карго-компании',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название склада')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Имя получателя')),
                ('recipient_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон склада')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкция по заполнению')),
                ('cargo_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='base.cargocompany', verbose_name='Карго-компания')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
    ]
