# Generated by Django 5.2 on 2026-04-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_site_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='cargo_company',
        ),
        migrations.DeleteModel(
            name='CargoCompany',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
