version: '3.8'

services:
  db_zeacargo:
    image: postgres:14
    container_name: postgres_db_zeacargo
    env_file:
      - ../.env
    volumes:
      - postgres_data_zeacargo:/var/lib/postgresql/data
    networks:
      - portfolio_network_zeacargo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_zeacargo:
    image: redis:6
    container_name: redis_zeacargo
    networks:
      - portfolio_network_zeacargo

  web_zeacargo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_zeacargo
    command: sh -c "/entrypoint.sh && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../app:/app
      - ../app/static:/app/static
      - ../app/media:/app/media
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    depends_on:
      db_zeacargo:
        condition: service_healthy
      redis_zeacargo:
        condition: service_started
    ports:
      - "8085:8000"
    networks:
      - portfolio_network_zeacargo

networks:
  portfolio_network_zeacargo:
    driver: bridge

volumes:
  postgres_data_zeacargo:
