# Generated by Django 5.2 on 2026-04-22 20:24

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[200, 200], upload_to='cargo/logos/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('address', models.TextField(blank=True, verbose_name='Адрес склада')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='Режим работы')),
                ('currency', models.CharField(choices=[('KGS', 'Сом (KGS)'), ('RUB', 'Рубль (RUB)'), ('KZT', 'Тенге (KZT)'), ('USD', 'Доллар (USD)')], default='KGS', max_length=3, verbose_name='Валюта')),
                ('bot_token', models.CharField(blank=True, max_length=200, verbose_name='Токен Telegram-бота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Карго-компания',
                'verbose_name_plural': 'Карго-компании',
                'ordering': ['-created_at'],
            },
        ),
    ]
